# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-13 18:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chairman',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('rating', models.IntegerField()),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('image_url', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[(b'M', b'MENTAL'), (b'P', b'PHYSICAL')], max_length=2)),
                ('reputation', models.IntegerField()),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('flag_url', models.CharField(max_length=255)),
                ('image_url', models.CharField(max_length=255)),
                ('wage', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Journalist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('image_url', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('rating', models.IntegerField()),
                ('image_url', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MediaCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('news_type', models.CharField(choices=[(b'G', b'GOOD'), (b'B', b'BAD')], max_length=1)),
                ('journalist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Journalist')),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image_url', models.CharField(max_length=255)),
                ('purchase_cost', models.IntegerField()),
                ('running_cost', models.IntegerField()),
                ('player_capacity', models.IntegerField()),
                ('level', models.IntegerField()),
                ('rating', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image_url', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('current_ability', models.IntegerField()),
                ('Potential_ability', models.IntegerField()),
                ('overall_ability', models.IntegerField()),
                ('performance', models.IntegerField()),
                ('happiness', models.IntegerField()),
                ('agency', models.CharField(max_length=255)),
                ('current_contract', models.IntegerField()),
                ('value', models.IntegerField()),
                ('bonus', models.IntegerField()),
                ('wins', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Scout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('rating', models.IntegerField()),
                ('hiring_fee', models.IntegerField()),
                ('image_url', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('rating', models.IntegerField()),
                ('image_url', models.CharField(max_length=255)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('league', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.League')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='current_club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Team'),
        ),
        migrations.AddField(
            model_name='player',
            name='interested_club',
            field=models.ManyToManyField(related_name='api_player_related', to='api.Team'),
        ),
        migrations.AddField(
            model_name='news',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Player'),
        ),
        migrations.AddField(
            model_name='journalist',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.MediaCompany'),
        ),
        migrations.AddField(
            model_name='chairman',
            name='team',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Team'),
        ),
    ]
