# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-15 18:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_auto_20170625_1834'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='UserCurrentTrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_list', models.TextField()),
                ('current_mental_coach', models.TextField()),
                ('current_physical_coach', models.TextField()),
                ('current_office', models.TextField()),
                ('upagrade_office_list', models.TextField()),
                ('current_scout_list', models.TextField()),
                ('base_commission', models.TextField()),
                ('transfer_commission', models.TextField()),
                ('sponsiorship_commission', models.TextField()),
                ('miscellanious_income', models.TextField()),
                ('miscellanious_expences', models.TextField()),
                ('staff_wage', models.TextField()),
                ('scout_hire_time', models.TextField()),
                ('scout_hire_duration', models.TextField()),
                ('physical_coach_hire_time', models.TextField()),
                ('physical_coach_hire_duration', models.TextField()),
                ('mental_coach_hire_time', models.TextField()),
                ('mental_coach_hire_duration', models.TextField()),
                ('current_week', models.TextField()),
                ('agency_reputation', models.TextField()),
                ('news_feed', models.TextField()),
                ('negotiations', models.TextField()),
                ('journalist_interactions', models.TextField()),
                ('mail_box', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
