# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-15 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_chat_usercurrenttrack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercurrenttrack',
            name='agency_reputation',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='usercurrenttrack',
            name='base_commission',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='usercurrenttrack',
            name='current_mental_coach',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='usercurrenttrack',
            name='current_office',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='usercurrenttrack',
            name='current_physical_coach',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='usercurrenttrack',
            name='current_scout_list',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='usercurrenttrack',
            name='current_week',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='usercurrenttrack',
            name='journalist_interactions',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='usercurrenttrack',
            name='mail_box',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='usercurrenttrack',
            name='mental_coach_hire_duration',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='usercurrenttrack',
            name='mental_coach_hire_time',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='usercurrenttrack',
            name='miscellanious_expences',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='usercurrenttrack',
            name='miscellanious_income',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='usercurrenttrack',
            name='negotiations',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='usercurrenttrack',
            name='news_feed',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='usercurrenttrack',
            name='physical_coach_hire_duration',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='usercurrenttrack',
            name='physical_coach_hire_time',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='usercurrenttrack',
            name='player_list',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='usercurrenttrack',
            name='scout_hire_duration',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='usercurrenttrack',
            name='scout_hire_time',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='usercurrenttrack',
            name='sponsiorship_commission',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='usercurrenttrack',
            name='staff_wage',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='usercurrenttrack',
            name='transfer_commission',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='usercurrenttrack',
            name='upagrade_office_list',
            field=models.TextField(null=True),
        ),
    ]
