# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-15 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20170715_1819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercurrenttrack',
            name='player_list',
        ),
        migrations.AddField(
            model_name='usercurrenttrack',
            name='player_list',
            field=models.ManyToManyField(to='api.Player'),
        ),
    ]
